stages:
  - build
  - test

include:
  - template: Container-Scanning.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml


.docker_build:
  image: docker:19.03.0-dind
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  stage: build
  script:
    - docker build -t $USER/docker-curl-ssh .
    - docker push $USER/docker-curl-ssh

Docker:
  extends: .docker_build
  variables:
    USER: cyb3rjak3
  before_script:
  - echo $DOCKER_TOKEN | docker login -u $USER --password-stdin

GitLab:
  extends: .docker_build
  variables:
    USER: registry.gitlab.com/cyb3r-jak3/docker-ssh-curl
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

GitLab-Scanning:
  extends: .docker_build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE