stages:
  - build
  - test

# include:
#   - template: Container-Scanning.gitlab-ci.yml


.docker_build:
  image: docker:19.03.0-dind
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  stage: build
  script:
    - docker build -t $USER/docker-curl-ssh .
    - docker push $USER/docker-curl-ssh

Docker:
  extends: .docker_build
  variables:
    USER: cyb3rjak3
  before_script:
  - docker login -u $USER -p $DOCKER_TOKEN

GitLab:
  extends: .docker_build
  variables:
    USER: registry.gitlab.com/cyb3r-jak3/docker-ssh-curl
  before_script:
  - docker login -u $USER -p $GITLAB_TOKEN registry.gitlab.com