build:
  image: docker:19.03.0-dind
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  stage: build
  before_script:
  - docker info
  - docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN
  script:
    - docker build -t cyb3rjake3/curl-ssh .
    - docker push cyb3rjak3/curl-ssh:latest